"""Stage5b — 裂变层扩展：把 decide.py 的轻量 creative_variants（脚本方向）
扩展为完整脚本，仅离线预生成 Top-N（默认20，按 decide.py 已有的 combined_score
排序）达人 × 各自 recommended_product 的完整创意脚本。

每个达人生成 4 个变体：TikTok竖版(15-30s) / YouTube横版(60-90s) × 中文/英文，
一次 DeepSeek 调用产出全部 4 个（省调用次数），验证后拆成 4 个缓存文件写盘，
key = {channel_id}_{product_id}_{platform}_{lang}.json，与 decide.py 一样可断点续跑。

Prompt 强制注入该达人的真实数据并要求模型显式引用：
  - 该频道播放量最高的真实视频标题
  - vision.py 输出的 8 维 content_vector（标注维度名）+ evidence 原文
  - 该 recommended_product 的 feature_breakdown 中分数最高的功能维度

验收（人工，非自动化相似度判分——见 PLAN.md §8.6）：换一个达人看是否还成立，
读起来像通用模板就回去改 prompt。

Run:
    python -m pipeline.scripts --top-n 20 --limit 3   # 验证：只跑前3个
    python -m pipeline.scripts --top-n 20              # 全量
"""
import argparse
import json
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from dotenv import load_dotenv

from pipeline.common.http import post_json
from pipeline.common.logging import get_logger

logger = get_logger("scripts")

ROOT = Path(__file__).resolve().parent
DECISIONS_CACHE_DIR = ROOT / "cache" / "decisions"
VISION_CACHE_DIR = ROOT / "cache" / "vision"
FEATURES_PATH = ROOT / "artifacts" / "features.json"
SCORES_PATH = ROOT / "artifacts" / "scores.json"
PRODUCTS_PATH = ROOT / "config" / "products.yaml"
SCRIPTS_CACHE_DIR = ROOT / "cache" / "scripts"
FAILURES_PATH = ROOT / "artifacts" / "scripts_failures.json"

MODEL_NAME = "deepseek-v4-flash"
BASE_URL = "https://api.deepseek.com"
DEFAULT_TOP_N = 20
MAX_RETRIES = 3
CONCURRENCY = 3

PLATFORMS = ["tiktok_vertical", "youtube_horizontal"]
LANGUAGES = ["zh", "en"]

DIMENSION_NAMES = [
    "第一人称视角占比", "防抖需求强度", "运镜复杂度", "场景极限度",
    "装备可见度", "叙事节奏", "场景多样性", "子弹时间/慢动作需求",
]


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def load_products() -> dict:
    import yaml
    with open(PRODUCTS_PATH, encoding="utf-8") as f:
        return {p["id"]: p for p in yaml.safe_load(f)["products"]}


def load_top_candidates(top_n: int) -> list[dict]:
    """Top-N decisions already generated by decide.py, re-sorted by the
    combined_score each decision already carries (no new ranking logic)."""
    decisions = []
    for p in DECISIONS_CACHE_DIR.glob("*.json"):
        d = _load_json(p)
        decisions.append({"channel_id": p.stem, "decision": d})
    decisions.sort(key=lambda x: -x["decision"]["combined_score"])
    return decisions[:top_n]


def top_video_title(channel: dict) -> str:
    videos = channel.get("videos") or []
    if not videos:
        return "（该频道无视频记录）"
    return max(videos, key=lambda v: v.get("view_count") or 0)["title"]


def top_feature_breakdown_dim(resonance_entry: dict) -> str:
    breakdown = resonance_entry.get("feature_breakdown") or {}
    if not breakdown:
        return "（无功能级共振数据）"
    return max(breakdown.items(), key=lambda kv: kv[1])[0]


def build_prompt(channel: dict, vision: dict, product: dict, resonance_entry: dict) -> list[dict]:
    content_vector = vision.get("content_vector") or []
    vector_lines = "\n".join(
        f"  {name}: {value:.2f}" for name, value in zip(DIMENSION_NAMES, content_vector)
    )
    video_title = top_video_title(channel)
    top_dim = top_feature_breakdown_dim(resonance_entry)

    system = (
        "你是Insta360全球达人营销团队的短视频编导。你要为一个具体的YouTube创作者写"
        "可以直接开拍的完整脚本，不是泛泛的方向性建议。脚本里必须明确引用下面给你的"
        "真实视频标题、视觉理解证据原文、以及点名的最高分功能维度——如果换一个创作者，"
        "这份脚本读起来不能成立。请以JSON格式输出，严格按照要求的字段结构，不要输出"
        "JSON之外的任何文字。"
    )
    user = f"""
【创作者档案】
频道名：{channel.get('title')}
垂类：{channel.get('vertical')}
播放量最高的真实视频标题：《{video_title}》

【推荐单品】
{product['name']}（{product['description']}）
该单品与本频道共振分最高的功能维度：{top_dim}

【视觉理解证据（GLM-4.6V-Flash 分析该频道真实缩略图/标题得出，8维语义向量）】
{vector_lines}
证据原文：{vision.get('evidence')}

请为这个创作者生成4条完整脚本，platform x language 四种组合各一条：
- platform="tiktok_vertical"：TikTok竖版，15-30秒
- platform="youtube_horizontal"：YouTube横版，60-90秒
- language="zh" 和 language="en" 各一版

每条脚本必须在 hook 或 voiceover_points 里明确提到上面给出的真实视频标题
《{video_title}》，并在某处引用/复述视觉证据原文里的具体描述（不是泛泛的"你的视频风格"），
同时说明为什么"{top_dim}"这个维度是本条脚本要着力展示的卖点。

输出如下JSON结构：
{{
  "variants": [
    {{
      "platform": "tiktok_vertical" | "youtube_horizontal",
      "language": "zh" | "en",
      "hook": "前3秒钩子文案",
      "storyboard_beats": ["分镜1", "分镜2", "..."],
      "voiceover_points": ["口播要点1", "口播要点2", "..."],
      "caption_copy": "字幕/文案文本",
      "cta_placement": "CTA出现的位置与内容",
      "referenced_evidence": {{
        "video_title": "{video_title}",
        "vision_evidence_quote": "从上面证据原文里引用/复述的具体句子",
        "top_feature_breakdown_dim": "{top_dim}"
      }}
    }}
  ]
}}
variants 数组必须正好包含4条，覆盖 (tiktok_vertical,zh)(tiktok_vertical,en)
(youtube_horizontal,zh)(youtube_horizontal,en) 四种组合各一条，不要遗漏或重复。
"""
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def call_deepseek(api_key: str, messages: list[dict]) -> dict:
    last_exc = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = post_json(
                f"{BASE_URL}/chat/completions",
                json={"model": MODEL_NAME, "messages": messages, "response_format": {"type": "json_object"}},
                headers={"Authorization": f"Bearer {api_key}"},
                timeout=(10, 90),
            )
            content = resp["choices"][0]["message"]["content"]
            data = json.loads(content)
            variants = data.get("variants")
            if not isinstance(variants, list) or len(variants) != 4:
                raise ValueError(f"expected exactly 4 variants, got {len(variants) if isinstance(variants, list) else variants!r}")
            seen = set()
            for v in variants:
                for field in ["platform", "language", "hook", "storyboard_beats", "voiceover_points",
                              "caption_copy", "cta_placement", "referenced_evidence"]:
                    if field not in v:
                        raise ValueError(f"variant missing field: {field}")
                if v["platform"] not in PLATFORMS or v["language"] not in LANGUAGES:
                    raise ValueError(f"unexpected platform/language: {v['platform']}/{v['language']}")
                seen.add((v["platform"], v["language"]))
            if len(seen) != 4:
                raise ValueError(f"variants must cover all 4 platform x language combos, got {seen}")
            return data
        except Exception as exc:
            last_exc = exc
            logger.warning("DeepSeek call failed (attempt %d/%d): %s", attempt, MAX_RETRIES, exc)
    raise last_exc


def process_one(api_key: str, channel_id: str, decision: dict, channels_by_id: dict,
                 products_by_id: dict, scores_by_id: dict) -> tuple[str, int]:
    channel = channels_by_id[channel_id]
    product_id = decision["recommended_product"]
    product = products_by_id[product_id]
    vision = _load_json(VISION_CACHE_DIR / f"{channel_id}.json")
    resonance_entry = scores_by_id[channel_id]["resonance"][product_id]

    messages = build_prompt(channel, vision, product, resonance_entry)
    llm_out = call_deepseek(api_key, messages)

    SCRIPTS_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    written = 0
    for v in llm_out["variants"]:
        cache_path = SCRIPTS_CACHE_DIR / f"{channel_id}_{product_id}_{v['platform']}_{v['language']}.json"
        payload = {**v, "model": MODEL_NAME}
        cache_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        written += 1
    return channel_id, written


def run(top_n: int, limit: int | None):
    load_dotenv(ROOT.parent / ".env")
    api_key = os.environ.get("DEEPSEEK_API_KEY")
    if not api_key:
        raise SystemExit("DEEPSEEK_API_KEY not set in .env")

    features_data = _load_json(FEATURES_PATH)
    scores_data = _load_json(SCORES_PATH)
    channels_by_id = {c["channel_id"]: c for c in features_data["channels"]}
    scores_by_id = scores_data["scores"]
    products_by_id = load_products()

    candidates = load_top_candidates(top_n)
    logger.info("%d decision-backed candidates ranked by combined_score (top_n=%d)", len(candidates), top_n)
    if limit:
        candidates = candidates[:limit]

    # skip candidates that already have all 4 cached variants (resumable)
    todo = []
    for cand in candidates:
        cid = cand["channel_id"]
        product_id = cand["decision"]["recommended_product"]
        existing = list(SCRIPTS_CACHE_DIR.glob(f"{cid}_{product_id}_*.json"))
        if len(existing) >= 4:
            logger.info("cached, skip: %s (%s)", cid, channels_by_id[cid]["title"])
            continue
        todo.append(cand)

    succeeded, failures = 0, []
    with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
        futures = {
            pool.submit(process_one, api_key, cand["channel_id"], cand["decision"], channels_by_id,
                        products_by_id, scores_by_id): cand
            for cand in todo
        }
        for fut in as_completed(futures):
            cand = futures[fut]
            title = channels_by_id[cand["channel_id"]]["title"]
            try:
                cid, written = fut.result()
                succeeded += 1
                logger.info("[%d/%d] OK: %s (%d variants written)", succeeded, len(todo), title, written)
            except Exception as exc:
                failures.append({"channel_id": cand["channel_id"], "title": title, "error": str(exc)})
                logger.error("FAILED: %s: %s", title, exc)

    if failures:
        FAILURES_PATH.parent.mkdir(parents=True, exist_ok=True)
        existing = _load_json(FAILURES_PATH) if FAILURES_PATH.exists() else []
        FAILURES_PATH.write_text(json.dumps(existing + failures, ensure_ascii=False, indent=2), encoding="utf-8")

    summary = {"candidates_considered": len(candidates), "processed_this_run": len(todo),
               "succeeded": succeeded, "failed": len(failures)}
    logger.info("=== DONE === %s", summary)
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--top-n", type=int, default=DEFAULT_TOP_N, help="candidate pool size (by combined_score)")
    parser.add_argument("--limit", type=int, default=None, help="only process first N candidates (validation)")
    args = parser.parse_args()
    print(json.dumps(run(args.top_n, args.limit), ensure_ascii=False, indent=2))
