import { useEffect, useState } from "react";
import type { CategoryId } from "./categories";

export type Dimension = { key: string; name: string; description: string };

/** A known, pre-vectorized product from pipeline/config/categories/<id>/products.yaml
 *  — the same vectors score.py uses for the precomputed ranking. Picking one of
 *  these in the chat re-scores creators against a REAL product instantly, with
 *  no DeepSeek call at all (unlike the free-text chat's model-guessed vector). */
export type CatalogProduct = { id: string; name: string; description: string; vector: number[] };

export type CatalogEntry = {
  label: string;
  status: "ready" | "onboarding";
  /** This category's axes, in vector order — what a productVector for THIS
   *  category must be scored against. Sent to /api/diagnose per-category so
   *  the model places a visitor's product on the right axes regardless of
   *  which category's dataset happens to be loaded in the browser. */
  dimensions: Dimension[];
  products: CatalogProduct[];
};

export type Catalog = Partial<Record<CategoryId, CatalogEntry>>;

// web/public/linkverse/catalog.json, generated by `python -m pipeline.export_catalog`
// from checked-in YAML config — available even on a fresh clone with no
// dataset.json built yet (see the script's docstring).
export function useCatalog(): Catalog | null {
  const [catalog, setCatalog] = useState<Catalog | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`${import.meta.env.BASE_URL}linkverse/catalog.json`)
      .then((r) => (r.ok ? r.json() : null))
      .then((data: Catalog | null) => {
        if (!cancelled) setCatalog(data);
      })
      .catch(() => {
        if (!cancelled) setCatalog(null);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return catalog;
}
